apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rwx
provisioner: example.com/nfs
parameters:
  archiveOnDelete: "false"
mountOptions:
  - vers=4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
