#https://github.com/rancher-sandbox/rancher-desktop/issues/5154
apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: nfs-server
      image: erichough/nfs-server
      env:
        - name: NFS_EXPORT_0
          value: /nfsdata
        - name: NFS_EXPORT_0_OPTIONS
          value: "*(rw,fsid=0,sync,no_subtree_check,no_root_squash,anonuid=0,anongid=0)"
      ports:
        - name: nfs
          containerPort: 2049
          hostPort: 2049
        - name: mountd
          containerPort: 20048
          hostPort: 20048
        - name: rpcbind
          containerPort: 111
          hostPort: 111
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
            - DAC_READ_SEARCH
      volumeMounts:
        - name: nfs-data
          mountPath: /nfsdata
  volumes:
    - name: nfs-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
