FROM osgeo/gdal:ubuntu-full-3.6.3

RUN apt update -y

RUN apt install -y  python3-pip git  curl

RUN pip install --upgrade pip setuptools wheel

COPY ./test_requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt