FROM python:3.11.2

ENV GID=99
ENV UID=1000

RUN apt update && \
    apt install -y sudo && \
    addgroup --gid $GID nonroot && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" nonroot && \
    echo 'nonroot ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN apt install -y buildah

RUN echo "unqualified-search-registries=[\"docker.io\"]" >> /etc/containers/registries.conf

USER nonroot

WORKDIR /app

RUN chmod -R 755 /app

COPY --chown=nonroot:nonroot ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

# SPECIFIC QUEUE HERE
CMD  cd /app && ~/.local/bin/celery -A acc_native_jobs worker --loglevel=INFO
