FROM python:3.11.2

ENV GID=99
ENV UID=1000

RUN apt update && \
    apt install -y sudo && \
    addgroup --gid $GID nonroot && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" nonroot && \
    echo 'nonroot ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN apt install -y buildah skopeo

RUN echo "unqualified-search-registries=[\"docker.io\"]" >> /etc/containers/registries.conf

USER nonroot

RUN mkdir /home/nonroot/app

WORKDIR /home/nonroot/app

# RUN chown -R nonroot:nonroot /home/nonroot/app

RUN chmod -R 755 /home/nonroot/app

COPY --chown=nonroot:nonroot ./requirements.txt /home/nonroot/app/requirements.txt

RUN pip install -r /home/nonroot/app/requirements.txt

# CMD sleep infinity

# SPECIFIC QUEUE HERE
CMD  sudo chown -R nonroot:nonroot /home/nonroot/app && cd ~/app && ~/.local/bin/celery -A acc_native_jobs worker -Q wkube --loglevel=INFO
