# This inbuilt stack expects requirements.txt file to be present in root folder

FROM python:3.7

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install -r /code/requirements.txt

COPY . .


CMD echo "This is default command output of predefined stack named PYTHON3_7"